// app/sitemap.js

export default async function sitemap() {
  return [
    {
      url: 'https://www.globalvisainternationals.com/',
      lastModified: new Date('2025-05-15'),
      changefreq: 'weekly',   // all lowercase
      priority: 1,
    },
    {
      url: 'https://www.globalvisainternationals.com/about-us',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/tourist-visa/canada',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/tourist-visa/australia',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/tourist-visa/usa',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/tourist-visa/uk',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/tourist-visa/europe',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/tourist-visa/japan',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/tourist-visa/dubai',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/tourist-visa/new-zealand',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/tourist-visa/singapore',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/student-visa/canada',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/student-visa/australia',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/student-visa/usa',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/student-visa/uk',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/student-visa/europe',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/student-visa/new-zealand',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/permanent-residency-visa/canada',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/permanent-residency-visa/australia',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/refusal-visa/canada',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/refusal-visa/australia',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/refusal-visa/usa',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/refusal-visa/uk',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/student-visa/europe',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/refusal-visa/new-zealand',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/us-green-card-2025-rules',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/English-language-requirements-for-The-UK',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/Schengen-Visa-Cascade',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/Basava-Jayanti-2025',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/Visa-Fee-Hack-for-Indian-Travelers',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/Australia-PR-Visa',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/career',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/contact',
      lastModified: new Date('2025-05-24'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/uk-student-visa-rules-2025',
      lastModified: new Date('2025-06-07'),
      changefreq: 'weekly',
      priority: 0.8,
    },

    {
      url: 'https://www.globalvisainternationals.com/blog/US-Visa-got-rejected-dont-wory',
      lastModified: new Date('2025-06-07'),
      changefreq: 'weekly',
      priority: 0.8,
    },


    {
      url: 'https://www.globalvisainternationals.com/blog/10-Plus-Countries-You-Can-Visit-With-A-USA-Visa',
      lastModified: new Date('2025-06-07'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/uk-evisa-digital-visa-replacement-2025',
      lastModified: new Date('2025-06-18'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/germany-steady-harbor-indian-students',
      lastModified: new Date('2025-06-18'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/US-Introduces-Sweeping-New-Rules-for-Foreign-Students-What-Indians-Need-to-Know',
      lastModified: new Date('2025-06-23'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/UK-Family-Visa-Tax-on-Love-2025',
      lastModified: new Date('2025-06-25'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/Canada-Plans-to-Introduce-New-Permanent-Residency-Program-in-2025/',
      lastModified: new Date('2025-06-23'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/10-Important-Things-to-Know-for-Indian-Students-in-Canada/',
      lastModified: new Date('2025-07-02'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/Italy-to-Issue-Nearly-500000-Work-Permits-to-Non-EU-Workers/',
      lastModified: new Date('2025-07-04'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/Visa-Friday-July-18-2025-Latest-Global-Visa-Updates-for-Indian-Travelers/',
      lastModified: new Date('2025-07-18'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/australian-tourist-visa-for-indians-july-2025-updates',
      lastModified: new Date('2025-08-05'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/Visa-updates-indians-august-2025',
      lastModified: new Date('2025-08-09'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/UK-Tourist-and-Student-Visa-Changes-in-2025',
      lastModified: new Date('2025-08-13'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/terms-and-conditions',
      lastModified: new Date('2025-08-13'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/An-invitation-letter-(from-a-U.S.-person)-guarantees-visa-approval',
      lastModified: new Date('2025-08-18'),
      changefreq: 'weekly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/Seen-as-Anti-American.-USA-May-Deny-You-a-Visa-What-the-New-Policy-Means',
      lastModified: new Date('2025-08-22'),
      changefreq: 'weekly',
      priority: 0.8,
    },

  ]
}