export default async function sitemap() {
  return [
    {
      url: 'https://www.globalvisainternationals.com/',
      lastModified: new Date('2025-05-15'),
      changefreq: 'weekly',   // all lowercase
      priority: 1.0,
    },
    {
      url: 'https://www.globalvisainternationals.com/about-us',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/tourist-visa/canada',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/tourist-visa/australia',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/tourist-visa/usa',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/tourist-visa/uk',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/tourist-visa/europe',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/tourist-visa/japan',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/tourist-visa/dubai',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/tourist-visa/new-zealand',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/tourist-visa/singapore',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/student-visa/canada',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/student-visa/australia',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/student-visa/usa',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/student-visa/uk',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/student-visa/europe',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/student-visa/new-zealand',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/permanent-residency-visa/canada',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/permanent-residency-visa/australia',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/refusal-visa/canada',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/refusal-visa/australia',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/refusal-visa/usa',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/refusal-visa/uk',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/student-visa/europe',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/Visa/refusal-visa/new-zealand',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/us-green-card-2025-rules',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/English-language-requirements-for-The-UK',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/Schengen-Visa-Cascade',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/Basava-Jayanti-2025',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/Visa-Fee-Hack-for-Indian-Travelers',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/blog/Australia-PR-Visa',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/career',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    {
      url: 'https://www.globalvisainternationals.com/contact',
      lastModified: new Date('2025-05-24'),
      changefreq: 'monthly',
      priority: 0.8,
    },
    // add more URLs here
  ]
}